account/urls.py
from django.urls import path
from . import views
from user import views as user_views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('edit/', user_views.edit_profile, name='edit_profile'),
]

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('inbox/', views.inbox, name='inbox'),
    path('t/<slug:slug>/', views.chat, name='chat'),
    path('send-message/', views.send_message, name='send_message'),
    path('new-chat/', views.new_chat, name='new_chat'),
    # path('get/users/', views.get_users, name='get_users')
]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views as user_views
from search import views as search_views
from post import views as post_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('feed.urls', namespace='feed')),
    path('accounts/', include('account.urls', namespace='account')),
    path('p/', include('post.urls', namespace='post')),
    path('direct/', include('chat.urls', namespace='chat')),
    path('user/', include('user.urls', namespace='user')),
    path('stories/', include('story.urls', namespace='story')),
    path('notification/', include('notification.urls', namespace='notification')),
    path('your-activity/', include('activity.urls', namespace='activity')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),

    # user views
    path('<str:username>/', user_views.profile, name='profile'),
    path('<str:username>/saved/', user_views.user_saved, name='user_saved'),
    path('explore/people/', user_views.suggestions, name='suggestions'),

    # post views
    path('explore/p/', post_views.explore, name='explore'),

    # search views
    path('search', search_views.search, name='search'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('create/', views.create_post, name='create_post'),
    path('<slug:slug>/', views.post_details, name='post_details'),
    path('<slug:slug>/comments/', views.get_post_comments, name='post_comments'),
    path('add-comment/<str:pk>/', views.add_comment, name='add_comment'),
    path('delete-comment/<str:pk>/', views.delete_comment, name='delete_comment'),
    path('add-like/<str:pk>/', views.add_like, name='add_like'),
    path('add-bookmark/<str:pk>/', views.add_bookmark, name='add_bookmark'),
    path('delete/<str:pk>/', views.delete_post, name='delete_post'),
    path('update/<slug:slug>/', views.update_post, name='update_post'),
    path('like-comment/<str:pk>/', views.like_comment, name='like_comment'),
    path('add-favorite/<str:user_id>/', views.add_favorites, name='add_favorites'),
    path('add-reply/<str:pk>/', views.add_reply, name='add_reply'),
    path('delete-reply/<str:pk>/', views.delete_reply, name='delete_reply'),
    path('like-reply/<str:pk>/', views.like_reply, name='like_reply'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [    
    path('follow/<str:user_id>/', views.follow, name='follow'),
    path('unfollow/<str:username>/', views.unfollow, name='unfollow'),
    path('remove/follower/<str:user_id>/', views.remove_follower, name='remove_follower'),
    path('upload-photo/<str:username>/', views.upload_profile_photo, name='upload_profile_photo'),
    path('create-highlight/<str:username>/', views.create_highlight, name='create_highlight'),
    path('edit-highlight/<slug:slug>/', views.edit_highlight, name='edit_highlight'),
    path('delete-highlight/<slug:slug>/', views.delete_highlight, name='delete_highlight'),
]

user/models.py
from django.db import models
from commons.models import StatusModel, TimeStampModel
from django.conf import settings
from story.models import Story
from post.random_slug import generate_random_slug

# Create your models here.

User = settings.AUTH_USER_MODEL

class Highlight(StatusModel, TimeStampModel):
    name = models.CharField(max_length=255, blank=True, null=True)
    slug = models.SlugField(max_length=255, db_index=True, unique=True, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    stories = models.ManyToManyField(Story, related_name='story_highlights', blank=True)

    def __str__(self):
        return f"{self.user}'s highlight - {self.name}"
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = generate_random_slug()
        super(Highlight, self).save(*args, **kwargs)

    @property
    def get_first_story(self):
        return self.stories.order_by('created_at').first()

user/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.db.models import Q, Count
from account.models import Profile
from account.forms import UserEditForm
from post.models import Post
from django.contrib.auth.decorators import login_required
from commons.decorators import normal_user_only
from .models import Highlight
from story.models import Story
from .decorators import highlight_user_required, user_required
from chat.utils import get_inbox

# Create your views here.

@normal_user_only
def profile(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    print(True if user.profile_photo else False)
    title = f'{user.name} (@{user.username}) | Instagram'
    user_posts = Post.objects.filter(user=user, status=True).order_by('-created_at')
    stories_count = Story.objects.filter(user = user).count()
    highlights = Highlight.objects.filter(user = user, status = True).order_by('-created_at').all()
    user_posts_count = user_posts.count()
    inbox = None
    if request.user != user:
        inbox = get_inbox(request.user, user)
    context = {'user':user, 'title':title, 'user_profile':True, 'user_posts':user_posts,
               'user_posts_count':user_posts_count, 'highlights':highlights, 'stories_count':stories_count, 'inbox':inbox}
    return render(request, 'user/profile/profile.html', context=context)

@login_required
@normal_user_only
@user_required
def user_saved(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    title = f'{user.name} (@{user.username}) \u2022 Instagram photos and videos'
    user_posts = Post.objects.filter(user=user, status=True).order_by('-created_at')
    stories_count = Story.objects.filter(user = user).count()
    highlights = Highlight.objects.filter(user = user, status = True).order_by('-created_at').all()
    user_posts_count = user_posts.count()
    user_bookmarks = user.profile.bookmarks.filter(status=True)
    context = {'user':user, 'title':title, 'user_bookmarks':user_bookmarks, 'bookmark':True, 
               'user_posts_count':user_posts_count, 'highlights':highlights, 'stories_count':stories_count}
    return render(request, 'user/profile/profile.html', context=context)

@login_required
def edit_profile(request):
    user = get_object_or_404(get_user_model(), username=request.user.username)
    form = UserEditForm(instance=user)
    if request.method == 'POST':
        form = UserEditForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated successfully.')
            return redirect('profile', username=user.username)
    context = {'form':form, 'user':user, 'edit_profile':True}
    return render(request, 'user/edit-profile.html', context=context)

@login_required
@normal_user_only
def upload_profile_photo(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    if request.method == 'POST':
        if request.FILES.get('profile_photo') is not None:
            uploaded_photo = request.FILES.get('profile_photo')
            user.profile_photo = uploaded_photo
            user.save()
            messages.success(request, 'Profile picture updated successfully.')
        else:
            messages.error(request, 'Please select an image to continue.')
    return redirect(request.META.get('HTTP_REFERER'))

@login_required
@normal_user_only
def suggestions(request):
    suggestions = get_user_model().objects.exclude(Q(id__in=request.user.profile.followings.all())|Q(id=request.user.id)|Q(is_superuser=True))
    context={'suggestions':suggestions}
    return render(request, 'user/suggestions.html', context=context)

@login_required
@normal_user_only
def follow(request, user_id):
    user = get_object_or_404(get_user_model(), id=user_id)
    if user not in request.user.profile.followings.all():
        request.user.profile.followings.add(user_id)
        user.profile.followers.add(request.user)
    return redirect(request.META.get('HTTP_REFERER'))

@login_required
@normal_user_only
def unfollow(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    if request.method == 'POST':
        if user in request.user.profile.followings.all():
            request.user.profile.followings.remove(user)
            user.profile.followers.remove(request.user)
            return redirect('profile', request.user.username)
    context = {'user':user}
    return render(request, 'user/unfollow.html',context=context)

@login_required
@normal_user_only
def remove_follower(request, user_id):
    user = get_object_or_404(get_user_model(), id=user_id)
    if user in request.user.profile.followers.all():
        request.user.profile.followers.remove(user_id)
        user.profile.followings.remove(request.user)
    return redirect(request.META.get('HTTP_REFERER'))

@login_required
@normal_user_only
def create_highlight(request, username):
    user = get_user_model().objects.select_related('profile').filter(username = username, is_active = True).first()
    if request.method == 'POST':
        name = request.POST.get('highlight_name')
        _stories = request.POST.getlist('story')
        if len(_stories) > 0:
            highlight = Highlight.objects.create(name = name, user = user)
            stories = Story.objects.filter(id__in = _stories, user = user).all()
            highlight.stories.add(*stories)
            messages.info(request, 'Highlight added.')
        else:
            messages.warning(request, 'Please select atleast one story.')
    return redirect(request.META.get('HTTP_REFERER'))

@login_required
@normal_user_only
def highlight_details(request, slug, story_slug):
    highlight = get_object_or_404(Highlight, slug = slug)
    story = get_object_or_404(Story, slug=story_slug)
    highlight_stories = Story.objects.filter(id__in = highlight.stories.all()).all()

    prev_story = Story.objects.filter(id__in = highlight.stories.all(), created_at__lt = story.created_at,).last()
    next_story = Story.objects.filter(id__in = highlight.stories.all(), created_at__gt = story.created_at,).first()

    context = {'highlight':highlight, 'story':story, 'highlight_stories':highlight_stories, 
               'prev_story':prev_story, 'next_story':next_story, 'title':'Stories', 'highlight_page':True}
    return render(request, 'user/highlight-details.html', context=context)

@login_required
@normal_user_only
@highlight_user_required
def edit_highlight(request, slug):
    highlight = get_object_or_404(Highlight, slug=slug)
    if request.method == 'POST':
        name = request.POST.get('highlight_name')
        _stories = request.POST.getlist('story')
        if name != highlight.name:
            highlight.name = name
            highlight.save()
        stories = Story.objects.filter(id__in = _stories)
        for story in stories:
            if story not in highlight.stories.all():
                highlight.stories.add(story)
    return redirect('profile', username=highlight.user.username)

@login_required
@normal_user_only
@highlight_user_required
def delete_highlight(request, slug):
    highlight = get_object_or_404(Highlight, slug=slug)
    highlight.delete()
    return redirect('profile', username = highlight.user.username)

templates/user/profile/profile-large-screen.html
{% load split_url %}
<div class="d-md-block d-none">
    <div class="row mb-3">
        <div class="col-4 text-center mb-5">
            <img src="{{user.profile_photo.url}}" alt="" class="profile-photo-avatar" {% if request.user == user %}data-bs-toggle="modal" data-bs-target="#picture-upload"{% endif %}>
        </div>
        <div class="col-8">
            <h1 class="mb-4"> 
                {{user.username}}
                &nbsp;
                {% if request.user == user %}
                    <a href="{% url 'account:edit_profile' %}" class="btn btn-light border rounded text-dark fw-bold">Edit profile</a>
                    &nbsp;
                    <a href="#" class="text-dark"><i class="bi bi-gear-wide" style="font-size:28px;"></i></a>
                {% else %}
                    {% if user in request.user.profile.followings.all %}
                        <a href="{% url 'user:unfollow' user.username %}" class="btn btn-light border rounded text-dark fw-bold" title="Following">
                            Following
                        </a>
                        <a href="{% url 'chat:chat' inbox.slug %}" class="btn btn-light border rounded text-dark fw-bold">Message</a>
                    {% else %}
                        {% if request.user in user.profile.followings.all %}
                            <a href="{% url 'user:follow' user.id %}" class="btn btn-primary fw-bold rounded" title="Follow Back">Follow Back</a>
                        {% else %}
                            <a href="{% url 'user:follow' user.id %}" class="btn btn-primary fw-bold rounded" title="Follow">Follow</a>
                        {% endif %}
                    {% endif %}
                    <a href="#" class="text-dark">
                        <i class="fas fa-ellipsis-h pt-2" style="font-size:20px;" data-bs-toggle="modal" data-bs-target="#profile-option-{{user.id}}"></i>
                    </a>
                {% endif %}
            </h1>
            <div class="fs-5 mb-4">
                <span class="fw-bold">{{user_posts_count}}</span> posts
                &ensp;
                <a data-bs-toggle="modal" data-bs-target="#followers-{{user.id}}" class="text-dark text-decoration-none" style="cursor:pointer">
                    <span class="fw-bold">{{user.profile.followers.count}}</span> followers
                </a>
                &ensp;
                <a data-bs-toggle="modal" data-bs-target="#following-{{user.id}}" class="text-dark text-decoration-none" style="cursor:pointer">
                    <span class="fw-bold">{{user.profile.followings.count}}</span> following
                </a>
            </div>
            <div class="fs-6">
                <b>{{user.name}}</b>
                <br>              
                {% if user.bio %}              
                    {{user.bio|linebreaks}}
                {% endif%}
                {% if user.website %}
                    <a href="{{user.website}}" class="text-decoration-none fw-bold" target="_blank">{{user.website|split_url}}</a>
                {% endif %}
            </div>
        </div>
        {% if stories_count > 0 %}
            <div class="px-5">
                {% include 'user/highlights.html' %}
            </div>
        {% endif %}
    </div>
</div>

templates/user/profile/profile-option-modal.html
<!-- Post Options Dropdown -->
{% load static %}
<div class="modal fade" id="profile-option-{{user.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered">
      <div class="modal-content rounded">
        <div class="modal-body">
          <ul class="list-group text-center">
            <li class="list-group-item">
              {% if request.user != user%}
                  <a href="#" class="text-decoration-none text-danger fw-bold">
                    Block
                  </a>
                {% endif %}
            </li>
            <li class="list-group-item">
              {% if request.user != user %}
                  <a href="#" class="text-decoration-none text-danger fw-bold">
                    Report
                  </a>
                {% endif %}
            </li>
            <li class="list-group-item">
              {% if request.user != user and user in request.user.profile.followings.all %}
                  <a href="{% url 'post:add_favorites' user.id %}" class="text-decoration-none text-dark">
                    {% if user not in request.user.profile.favourites.all %}
                        Add to favorites
                    {% else %}
                        Remove from favorites
                    {% endif %}
                  </a>
                {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </div>
</div>

templates/user/profile/profile-small-screen.html
{% load split_url %}
<div class="d-md-none d-sm-block">
    <div class="row mb-3">
        <div class="col-4 mb-5 text-start">
            <img src="{{user.profile_photo.url}}" alt="" class="profile-small-image-avatar" {% if request.user == user %}data-bs-toggle="modal" data-bs-target="#picture-upload"{% endif %}>
        </div>
        <div class="col-8 text-start">
            <h2 class="mb-2">
            {{user.username}}
            {% if request.user == user %}
                <a href="#" class="text-dark pt-1"><i class="bi bi-gear-wide" style="font-size:24px;"></i></a></h2>
                <a href="{% url 'account:edit_profile' %}" class="btn btn-light border rounded text-dark fw-bold w-100 btn-sm">Edit profile</a>
            {% else %}
                <a href="#" class="text-dark">
                    <i class="fas fa-ellipsis-h pt-2" style="font-size:20px;" data-bs-toggle="modal" data-bs-target="#profile-option-{{user.id}}"></i>
                </a>
                <div class="mt-2">
                    {% if user in request.user.profile.followings.all %}
                        <a href="{% url 'user:unfollow' user.username %}" class="btn btn-light border btn-sm rounded text-dark fw-bold">
                            Following
                        </a>
                        <a href="{% url 'chat:chat' inbox.slug %}" class="btn btn-light border btn-sm rounded text-dark fw-bold">Message</a>
                    {% else %}
                        {% if request.user in user.profile.followings.all %}
                            <a href="{% url 'user:follow' user.id %}" class="btn btn-primary btn-sm fw-bold rounded" title="Follow Back">Follow Back</a>
                        {% else %}
                            <a href="{% url 'user:follow' user.id %}" class="btn btn-primary btn-sm fw-bold rounded" title="Follow">Follow</a>
                        {% endif %}
                    {% endif %}
                </div>
            {% endif %}
            
        </div>
        <div class="col-12 fs-6">
            {{user.name}}
            {% if user.bio %}              
                {{user.bio|linebreaks}}
            {% endif%}
            {% if user.website %}
                <a href="{{user.website}}" class="text-decoration-none fw-bold" target="_blank">{{user.website|split_url}}</a>
            {% endif %}
        </div>
        {% if stories_count > 0 %}
            <div class="px-1">
                {% include 'user/highlights.html' %}
            </div>
        {% endif %}
        <div class="fs-5 mb-4 d-flex justify-content-around">
            <a class="text-dark text-decoration-none text-center disabled">
                <span class="fw-bold">{{user_posts_count}}</span>
                <br>
                <span class="text-muted fs-6">posts</span>
            </a>
            &ensp;
            <a class="text-dark text-decoration-none text-center" data-bs-toggle="modal" data-bs-target="#followers-{{user.id}}" class="" style="cursor:pointer">
                <span class="fw-bold">{{user.profile.followers.count}}</span>
                <br>
                <span class="text-muted fs-6">followers</span>
            </a>
            &ensp;
            <a class="text-dark text-decoration-none text-center" data-bs-toggle="modal" data-bs-target="#following-{{user.id}}" class="text-dark text-decoration-none" style="cursor:pointer">
                <span class="fw-bold">{{user.profile.followings.count}}</span>
                <br>
                <span class="text-muted fs-6">following</span>
            </a>
        </div>
    </div>
</div>

templates/user/profile/profile.html
{% extends 'layouts/main-layout.html' %}

{% block content %}
    <div class="container my-5">
        <!-- Large screen -->
        {% include './profile-large-screen.html' %}
        <!-- Large screen -->
        <!-- Small screen -->
        {% include './profile-small-screen.html' %}
        <!-- Small Screen -->
        <hr>
        <ul class="nav nav-pills justify-content-center">
            <li class="nav-item">
            <a class="nav-link {% if user_profile %}active disabled{% endif %}" href="{{ user.get_absolute_url }}"><i class="bi bi-table"></i>&nbsp;POSTS</a>
            </li>
            {% if request.user == user %}
                <li class="nav-item">
                    <a class="nav-link {% if bookmark %}active disabled{% endif %}" href="{% url 'user_saved' user.username %}"><i class="bi bi-bookmark-fill"></i>&nbsp;SAVED</a>
                </li>
            {% endif %}
        </ul>
        {% if not bookmark %}
            {% if user_posts %}
                <div class="mx-auto">
                    {% include 'user/user-posts.html' %}
                </div>
            {% else %}
                <div class="text-center mt-5">
                    <i class="fas fa-camera mb-5" style="font-size: 48px;"></i>
                    <h1 class="fs-1">No Posts Yet</h1>
                </div>
            {% endif %}
        {% else %}
            {% if user_bookmarks %}
                <div class="mx-auto">
                    {% include 'user/user-bookmarks.html' %}
                </div>
            {% else %}
                <div class="text-center mt-5">
                    <i class="fas fa-bookmark mb-5" style="font-size: 48px;"></i>
                    <h1 class="fs-1">No Bookmarks</h1>
                </div>
            {% endif %}
        {% endif %}
        
    </div> 
    {% include 'user/profile-picture-upload-modal.html' %} 
    {% include 'user/highlights-create-modal.html' %}
    {% include 'user/follower-modal.html' %}
    {% include 'user/following-modal.html' %}
    {% include 'user/profile/profile-option-modal.html' %}

{% endblock content %}