chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('inbox/', views.inbox, name='inbox'),
    path('t/<slug:slug>/', views.chat, name='chat'),
    path('send-message/', views.send_message, name='send_message'),
    path('new-chat/', views.new_chat, name='new_chat'),
    # path('get/users/', views.get_users, name='get_users')
]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views as user_views
from search import views as search_views
from post import views as post_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('feed.urls', namespace='feed')),
    path('accounts/', include('account.urls', namespace='account')),
    path('p/', include('post.urls', namespace='post')),
    path('direct/', include('chat.urls', namespace='chat')),
    path('user/', include('user.urls', namespace='user')),
    path('stories/', include('story.urls', namespace='story')),
    path('notification/', include('notification.urls', namespace='notification')),
    path('your-activity/', include('activity.urls', namespace='activity')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),

    # user views
    path('<str:username>/', user_views.profile, name='profile'),
    path('<str:username>/saved/', user_views.user_saved, name='user_saved'),
    path('explore/people/', user_views.suggestions, name='suggestions'),

    # post views
    path('explore/p/', post_views.explore, name='explore'),

    # search views
    path('search', search_views.search, name='search'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

story/urls.py
from django.urls import path
from . import views
from user import views as user_views

app_name = 'story'

urlpatterns = [
    path('details/<str:username>/<slug:slug>/', views.story_details, name='story_details'),
    path('add-to-story/', views.add_to_story, name='add_to_story'),
    path('like-story/<slug:slug>/', views.like_story, name='like_story'),
    path('reply-story/<slug:slug>/', views.reply_to_story, name='reply_to_story'),
    path('delete-story/<slug:slug>/', views.delete_story, name='delete_story'),
    path('highlights/<slug:slug>/<slug:story_slug>/', user_views.highlight_details, name='highlight_details'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [    
    path('follow/<str:user_id>/', views.follow, name='follow'),
    path('unfollow/<str:username>/', views.unfollow, name='unfollow'),
    path('remove/follower/<str:user_id>/', views.remove_follower, name='remove_follower'),
    path('upload-photo/<str:username>/', views.upload_profile_photo, name='upload_profile_photo'),
    path('create-highlight/<str:username>/', views.create_highlight, name='create_highlight'),
    path('edit-highlight/<slug:slug>/', views.edit_highlight, name='edit_highlight'),
    path('delete-highlight/<slug:slug>/', views.delete_highlight, name='delete_highlight'),
]

story/models.py
from django.db import models
from commons.models import TimeStampModel, StatusModel
from django.contrib.auth.models import BaseUserManager
from django.conf import settings
from post.random_slug import generate_random_slug
from django.urls import reverse

# Create your models here.

User = settings.AUTH_USER_MODEL

class Story(TimeStampModel, StatusModel):
    caption = models.CharField(max_length=500, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    slug = models.SlugField(max_length=255, db_index=True, unique=True, blank=True, null=True)
    image = models.ImageField(upload_to='story', blank=True, null=True)
    likes = models.ManyToManyField(User, related_name='story_likes', blank=True)
    views = models.ManyToManyField(User, related_name='story_viewers', blank=True)

    def __str__(self):
        return f"{self.user}'s story - {self.caption}"
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = generate_random_slug()
        super(Story, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('story:story_details', kwargs={'username':self.user.username, 'slug':self.slug})

    class Meta:
        ordering = ['created_at']
        verbose_name_plural = 'stories'


class StoryReply(TimeStampModel, StatusModel):
    story = models.ForeignKey(Story, on_delete=models.CASCADE, related_name='story_replies', blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    body = models.TextField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"{self.user}'s reply"

    class Meta:
        ordering = ['-created_at']

    

story/forms.py
from django import forms
from .models import Story, StoryReply


class StoryForm(forms.ModelForm):

    caption = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control mb-2 rounded', 'placeholder':'Write a caption'}))
    image = forms.ImageField(required=True, widget=forms.FileInput(attrs={'class': 'form-control rounded mb-2', 'placeholder':'Your story image'}))

    class Meta:
        model = Story
        fields = ['caption', 'image']


class StoryReplyForm(forms.ModelForm):
    body = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control rounded', 'placeholder':'Add your message here...'}))

    class Meta:
        model = StoryReply
        fields = ['body']

story/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from .models import Story
from .forms import StoryForm, StoryReplyForm
from django.contrib import messages
from .decorators import increament_story_view_count, story_user_required, redirect_to_home_on_story_expire
from commons.decorators import normal_user_only
from feed.decorators import remove_old_stories

# Create your views here.

User = get_user_model()

@login_required
@redirect_to_home_on_story_expire
@remove_old_stories
@increament_story_view_count
def story_details(request, username, slug):
    user = get_user_model().objects.filter(username=username).first()
    story = Story.objects.filter(user = user, slug = slug, status = True).first()
    user_stories = Story.objects.filter(user=user, status = True).all()
    prev_story = Story.objects.filter(user = user, created_at__lt = story.created_at, status = True).last()
    next_story = Story.objects.filter(user = user, created_at__gt = story.created_at, status = True).first()
    story_reply_form = StoryReplyForm()
    context = {'user':user, 'story':story, 'user_stories':user_stories, 
               'prev_story':prev_story, 'next_story':next_story, 
               'story_reply_form':story_reply_form, 'title':'Stories', 'story_page':True}
    return render(request, 'story/story-details.html', context=context)

@login_required
@normal_user_only
def add_to_story(request):
    if request.method == 'POST':
        caption = request.POST.get('caption')
        images = request.FILES.getlist('images')      
        for image in images:
            Story.objects.create(caption=caption, user=request.user, image=image)
            messages.success(request, 'Your story updated successfully.')
    return redirect(request.META.get('HTTP_REFERER'))

@login_required
@normal_user_only
def like_story(request, slug):
    story = get_object_or_404(Story, slug=slug)
    if request.user not in story.likes.all():
        story.likes.add(request.user)
    else:
        story.likes.remove(request.user)
    return redirect(request.META.get('HTTP_REFERER'))

@login_required
@normal_user_only
def reply_to_story(request, slug):
    story = get_object_or_404(Story, slug=slug)
    if request.method == 'POST':
        story_reply_form = StoryReplyForm(request.POST)
        if story_reply_form.is_valid():
            story_reply = story_reply_form.save(commit = False)
            story_reply.story = story
            story_reply.user = request.user
            story_reply.save()
            messages.success(request, 'Message sent.')
        else:
            messages.error(request, 'Something went wrong.')
    return redirect(request.META.get('HTTP_REFERER'))

@login_required
@normal_user_only
@story_user_required
def delete_story(request, slug):
    story = get_object_or_404(Story, slug=slug)
    story.status=False
    story.save()
    messages.info(request, 'Story deleted.')
    return redirect('/')

templates/story/story-create-modal.html
<div class="modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" id="add-to-story">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content rounded-4">
          <div class="modal-header">
            <h6 class="modal-title" id="exampleModalLabel">Story</h6>
            <form method="post" action="{% url 'story:add_to_story' %}" enctype="multipart/form-data">
            <button type="submit" class="btn btn-link btn-sm text-decoration-none">Create</button>
          </div>
          <div class="modal-body">
                {% csrf_token %}
              <div class="form-floating mb-3">
                <!-- {{story_form.caption}} -->
                <input type="text" name="caption" class="form-control mb-2 rounded" placeholder="Write a caption">
                <label for="caption" class="col-form-label">Write a caption</label>
              </div>
              <div class="mb-3">
                <label for="image" class="col-form-label">Story image</label>
                <!-- {{story_form.image}} -->
                <input type="file" name="images" class="form-control mb-2 rounded" placeholder="Your story image" multiple>
              </div>        
            </form>
          </div>
        </div>
    </div>
</div>

templates/story/story-details.html
{% extends 'layouts/story-layout.html' %}
{% load static %}
{% load format_created_at %}
{% block content %}

<div class="row">
  <div class="col-md-10 mx-auto px-3">
      <div class="row">
          <div class="col-md-6 px-3 mx-auto">
            <div class="card shadow rounded border-info">
              <div class="story-image">
                <img src="{{story.image.url}}" class="card-img-top" alt="...">
              </div>
              <div class="card-img-overlay text-center story-image">
                <h5 class="card-title fw-bold fs-1">{{story.caption}}</h5>
              </div>
              <div class="card-body text-center">
                <div class="d-flex justify-content-between mb-4 px-3">
                  <a href="{{ story.user.get_absolute_url }}" class="d-flex justify-content-start text-decoration-none text-dark">
                      <img src="{{story.user.profile_photo.url}}" class="me-2 post-profile-avatar">
                      <h6 class="fw-bold pt-2">{{story.user.username}}
                        &bull;
                        <small class="text-muted">{{story.created_at|format_created_time}}</small>
                      </h6>
                  </a>
                  <div class="dropdown">
                    <i class="fas fa-ellipsis-h pt-2" data-bs-toggle="dropdown" data-bs-auto-close="outside" style="cursor:pointer;"></i>
                    {% include 'story/story-options-dropdown.html' %}
                  </div>
                </div>

                {% if request.user != story.user %}
                  <form action="{% url 'story:reply_to_story' story.slug %}" method="post" class="px-3">
                    {% csrf_token %}
                    <div class="row g-0">
                      <div class="col-sm-10">
                        {{story_reply_form.body}}
                      </div>
                      <div class="col-sm-2">
                        <a href="{% url 'story:like_story' story.slug %}" class="text-decoration-none text-dark">
                          {% if request.user in story.likes.all %}
                            <i class="fas fa-heart py-1" style="font-size:30px; color: crimson;"></i>
                          {% else %}
                            <i class="far fa-heart py-1" style="font-size:30px;"></i>
                          {% endif %}
                        </a>
                      </div>
                    </div>
                  </form>
                {% else %}
                  <div class="d-flex justify-content-between my-2 px-3">
                    <button type="button" class="btn btn-dark rounded" data-bs-toggle="modal" data-bs-target="#story-{{story.id}}-views"><i class="fas fa-eye"></i>&nbsp;{{story.views.count}}</button>
                    <div class="d-flex justify-content-center">
                      <button type="button" class="btn btn-outline-primary rounded me-1" data-bs-toggle="modal" data-bs-target="#story-{{story.id}}-replies"><i class="fas fa-comment"></i>&nbsp;{{story.story_replies.count}}</button>
                      <button type="button" class="btn btn-danger rounded" data-bs-toggle="modal" data-bs-target="#story-{{story.id}}-likes"><i class="fas fa-heart"></i>&nbsp;{{story.likes.count}}</button>
                    </div>
                  </div>
                {% endif %}
              </div>
            </div>
          </div>
      </div>
  </div>
</div>

<div class="d-flex justify-content-between text-center mt-2">
  {% if prev_story %}
    <a href="{% url 'story:story_details' user.username prev_story.slug %}" class="btn btn-dark btn-sm rounded">&#8249;</a>
  {% else %}
    <a href="#" class="btn btn-dark btn-sm rounded float-start disabled">&#8249;</a>
  {% endif %}

  <div class="text-center mx-auto">
    {% for user_story in user_stories %}
      {% if user_story.id == story.id %}
        {{forloop.counter}} of {{user_stories.count}}
      {% endif %}
    {% endfor %}
  </div>

  {% if next_story %}
    <a href="{% url 'story:story_details' user.username next_story.slug %}" class="btn btn-dark btn-sm rounded">&#8250;</a>
  {% else %}
    <a href="#" class="btn btn-dark btn-sm rounded float-end disabled">&#8250;</a>
  {% endif %}
</div>

{% include 'story/story-like-modal.html' %}
{% include 'story/story-reply-modal.html' %}
{% include 'story/story-views-modal.html' %}

{% endblock content%}

templates/story/story-like-modal.html
<!-- Post Likes Modal -->
{% load static %}
<div class="modal" id="story-{{story.id}}-likes" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered">
        <div class="modal-content rounded">
            <div class="modal-header text-center">
                <h5 class="modal-title w-100">
                    Likes
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <ol class="list-group list-group-flush">
                    {% for liker in story.likes.all %}
                        <li class="list-group-item d-flex justify-content-between align-items-start" style="border: none">
                            <a href="{{ liker.get_absolute_url }}" class="text-decoration-none text-dark">
                            <img src={{liker.profile_photo.url}} alt="" class="post-profile-avatar">
                            <div class="ms-2 me-auto fs-6">
                                <div class="fw-bold">{{liker.username}}</a></div>
                                <span class="text-muted">{{liker.name}}</span>
                            </div>
                            <span>
                                {% if liker != request.user %}
                                    {% if liker in request.user.profile.followings.all %}
                                        <a href="{% url 'user:unfollow' liker.username %}" class="fw-bold btn btn-light btn-sm border rounded">Following</a>
                                    {% else %}
                                        <a href="{% url 'user:follow' liker.id %}" class="fw-bold btn btn-primary btn-sm rounded">Follow</a>
                                    {% endif %}
                                {% endif %}
                            </span>
                        </li>
                    {% endfor %}
                </ol>
            </div>
        </div>
    </div>
</div>

templates/story/story-option-modal.html
<!-- Story Options Modal -->
{% load static %}
<div class="modal" id="story-option-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content rounded">
            <div class="modal-body">
                <ul class="list-group">
                    {% if my_active_story_count %}
                        <a href="{{request.user.get_first_active_story.get_absolute_url}}" class="btn btn-light w-100 text-start">View Story</a>
                    {% endif %}
                    <a href="#" class="btn btn-light w-100 text-start" data-bs-toggle="modal" data-bs-target="#add-to-story">
                        Add to Story
                    </a>
                </ul>
            </div>
        </div>
    </div>
</div>
{% include 'story/story-create-modal.html' %}

templates/story/story-options-dropdown.html
<!-- Post Options Dropdown -->
{% load static %}
<ul class="dropdown-menu dropdown-menu-start dropdown-menu-lg-end text-center rounded">
    {% if request.user == story.user %}
        <a href="{% url 'story:delete_story' story.slug %}" class="dropdown-item text-danger fw-bold">Delete</a>
    {% else %}
        <a href="#" class="dropdown-item text-danger fw-bold">Report</a>
    {% endif %}
</ul>

templates/story/story-reply-modal.html
<!-- Post Likes Modal -->
{% load static %}
{% load format_created_at %}

<div class="modal" id="story-{{story.id}}-replies" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered">
        <div class="modal-content rounded">
            <div class="modal-header text-center">
                <h5 class="modal-title w-100">
                    Replies
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% for reply in story.story_replies.all %}
                    <ul class="list-group list-group-horizontal">
                        <li class="list-group-item" style="border: none">
                            <img src={{reply.user.profile_photo.url}} alt="" class="post-profile-avatar"> 
                        </li>
                        <li class="list-group-item" style="border: none;">
                            <b>{{reply.user.username}}</b> <small class="ms-1 text-muted">{{reply.created_at|format_created_time}}</small>
                            <p>{{reply.body}}</p>
                            <span class="small text-muted d-flex justify-content-start">
                                <div class="dropdown">
                                    <i class="fas fa-ellipsis-h pt-1 me-3" style="cursor:pointer;" data-bs-toggle="dropdown" aria-expanded="false"></i>
                                    <ul class="dropdown-menu text-center dropdown-menu-start" aria-labelledby="dropdownMenuButton1">
                                        <li><a class="dropdown-item text-danger fw-bold" href="#">Report</a></li>
                                    </ul>
                                </div>
                            </span> 
                        </li>
                    </ul>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

templates/story/story-views-modal.html
<!-- Post Likes Modal -->
{% load static %}
<div class="modal" id="story-{{story.id}}-views" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered">
        <div class="modal-content rounded">
            <div class="modal-header text-center">
                <h5 class="modal-title w-100">
                    Views
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <ol class="list-group list-group-flush">
                    {% for liker in story.views.all %}
                        <li class="list-group-item d-flex justify-content-between align-items-start" style="border: none">
                            <a href="{{ liker.get_absolute_url }}" class="text-decoration-none text-dark">
                            <img src={{liker.profile_photo.url}} alt="" class="post-profile-avatar">
                            <div class="ms-2 me-auto fs-6">
                                <div class="fw-bold">{{liker.username}}</a></div>
                                <span class="text-muted">{{liker.name}}</span>
                            </div>
                            <span>
                                {% if liker != request.user %}
                                    {% if liker in request.user.profile.followings.all %}
                                        <a href="{% url 'user:unfollow' liker.username %}" class="fw-bold btn btn-light btn-sm border rounded">Following</a>
                                    {% else %}
                                        <a href="{% url 'user:follow' liker.id %}" class="fw-bold btn btn-primary btn-sm rounded">Follow</a>
                                    {% endif %}
                                {% endif %}
                            </span>
                        </li>
                    {% endfor %}
                </ol>
            </div>
        </div>
    </div>
</div>