activity/urls.py
from django.urls import path
from . import views

app_name = 'activity'

urlpatterns = [
    path('interactions/likes/', views.likes, name='likes'),
    path('interactions/comments/', views.comments, name='comments'),
    path('interactions/story-replies/', views.story_replies, name='story_replies'),
    path('photos/posts/', views.posts, name='posts'),
    path('photos/highlights/', views.highlights, name='highlights'),
]

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('inbox/', views.inbox, name='inbox'),
    path('t/<slug:slug>/', views.chat, name='chat'),
    path('send-message/', views.send_message, name='send_message'),
    path('new-chat/', views.new_chat, name='new_chat'),
    # path('get/users/', views.get_users, name='get_users')
]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views as user_views
from search import views as search_views
from post import views as post_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('feed.urls', namespace='feed')),
    path('accounts/', include('account.urls', namespace='account')),
    path('p/', include('post.urls', namespace='post')),
    path('direct/', include('chat.urls', namespace='chat')),
    path('user/', include('user.urls', namespace='user')),
    path('stories/', include('story.urls', namespace='story')),
    path('notification/', include('notification.urls', namespace='notification')),
    path('your-activity/', include('activity.urls', namespace='activity')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),

    # user views
    path('<str:username>/', user_views.profile, name='profile'),
    path('<str:username>/saved/', user_views.user_saved, name='user_saved'),
    path('explore/people/', user_views.suggestions, name='suggestions'),

    # post views
    path('explore/p/', post_views.explore, name='explore'),

    # search views
    path('search', search_views.search, name='search'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

story/urls.py
from django.urls import path
from . import views
from user import views as user_views

app_name = 'story'

urlpatterns = [
    path('details/<str:username>/<slug:slug>/', views.story_details, name='story_details'),
    path('add-to-story/', views.add_to_story, name='add_to_story'),
    path('like-story/<slug:slug>/', views.like_story, name='like_story'),
    path('reply-story/<slug:slug>/', views.reply_to_story, name='reply_to_story'),
    path('delete-story/<slug:slug>/', views.delete_story, name='delete_story'),
    path('highlights/<slug:slug>/<slug:story_slug>/', user_views.highlight_details, name='highlight_details'),
]

activity/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from commons.models import TimeStampModel, StatusModel
from django.contrib.auth.models import BaseUserManager
from django.conf import settings
from .random_slug import generate_random_slug
from django.urls import reverse

# Create your models here.

User = settings.AUTH_USER_MODEL

class Post(TimeStampModel, StatusModel):
    caption = models.CharField(max_length=255, blank=True, null=True)
    slug = models.SlugField(max_length=255, db_index=True, unique=True, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    likes = models.ManyToManyField(User, related_name='post_likes', blank=True)

    def __str__(self):
        return self.caption

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = generate_random_slug()
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('post:post_details', kwargs={'slug':self.slug})
    
    @property
    def get_like_url(self):
        return reverse('post:add_like', args=[self.id])
    
    @property
    def get_bookmark_url(self):
        return reverse('post:add_bookmark', args=[self.id])

    class Meta:
        ordering = ['-created_at']


class PostImage(TimeStampModel, StatusModel):
    image = models.ImageField(upload_to='post', blank=True, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.post.caption

class CommentManager(BaseUserManager):
    def get_queryset(self):
        return super().get_queryset().filter(status=True)
    
    
class Comment(TimeStampModel, StatusModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_comments', blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comments', blank=True, null=True)
    body = models.TextField(max_length=255, blank=True, null=True)
    likes = models.ManyToManyField(User, related_name='comment_likes', blank=True)
    objects = CommentManager()

    def __str__(self):
        return f"{self.user} commented on '{self.post}': '{self.body}'"


class Reply(TimeStampModel, StatusModel):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='comment_replies', blank=True, null=True)
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='reply_replies', blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_replies', blank=True, null=True)
    body = models.TextField(max_length=255, blank=True, null=True)
    likes = models.ManyToManyField(User, related_name='reply_likes', blank=True)
    objects = CommentManager()

    class Meta:
        ordering = ['created_at']
        verbose_name_plural = 'replies'

    @property
    def replied_user(self):
        return self.reply.user if self.reply else self.comment.user

    def __str__(self):
        return f"{self.user} replied to your comment '{self.comment}': '{self.body}'"

activity/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import get_user_model
from post.models import Post, Comment
from story.models import Story, StoryReply
from user.models import Highlight
from itertools import chain

# Create your views here.

def likes(request):
    user = get_object_or_404(get_user_model(), username=request.user.username)
    liked_posts = user.post_likes.all()
    context = {'liked_posts':liked_posts, 'likes':True, 'interactions':True}
    return render(request, 'activity/interactions.html', context=context)

def comments(request):
    user = get_object_or_404(get_user_model(), username=request.user.username)
    user_comments = user.user_comments.all()
    user_replies = user.user_replies.all()
    all_comments = sorted(chain(user_comments, user_replies), key=lambda instance: instance.created_at, reverse=True)
    context = {'all_comments':all_comments, 'comments':True, 'interactions':True, 'category':'all'}
    
    category = request.GET.get('category')

    if category == 'all':
        context.update({'all_comments':all_comments})
    elif category == 'comments':
        context.update({'all_comments':user_comments, 'category':'comments'})
    elif category == 'replies':
        context.update({'all_comments':user_replies, 'category':'replies'})

    return render(request, 'activity/interactions.html', context=context)

def story_replies(request):
    user = get_object_or_404(get_user_model(), username=request.user.username)
    story_replies = user.storyreply_set.all()
    context = {'story_replies':story_replies, 'story_replies_tab':True, 'interactions':True}
    return render(request, 'activity/interactions.html', context=context)

def posts(request):
    user = get_object_or_404(get_user_model(), username=request.user.username)
    user_posts = Post.objects.filter(user=user, status=True).order_by('-created_at')
    context = {'user_posts':user_posts, 'posts':True, 'photos':True}
    return render(request, 'activity/photos.html', context=context)

def highlights(request):
    user = get_object_or_404(get_user_model(), username=request.user.username)
    user_highlights = Highlight.objects.filter(user=user, status=True).order_by('-created_at')
    context = {'user_highlights':user_highlights, 'highlights':True, 'photos':True}
    return render(request, 'activity/photos.html', context=context)

templates/activity/interactions.html
{% extends 'layouts/main-layout.html' %}
{% load static %}
{% load format_created_at %}
{% block content %}

<div class="container">
    <div class="row mx-auto">
        <div class="col-12 col-lg-8 mx-auto my-3">
            <h3 class="fw-bold my-3">Your activity</h3>
            <div class="card rounded">
                <div class="card-body">
                    <ul class="nav nav-pills nav-justified mb-3">
                        <li class="nav-item">
                          <a class="nav-link {% if interactions %}active{% endif %}" aria-current="page" href="#"><i class="bi bi-arrow-left-right"></i>&nbsp;Interactions</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link {% if photos %}active{% endif %}" href="{% url 'activity:posts' %}"><i class="bi bi-images"></i>&nbsp;Photos</a>
                        </li>
                    </ul>
                    <ul class="nav nav-tabs justify-content-center">
                        <li class="nav-item">
                          <a class="nav-link {% if likes %}active{% endif %}" aria-current="page" href="{% url 'activity:likes' %}" title="Likes"><i class="bi bi-heart"></i> <span class="ms-1 d-md-inline d-none">LIKES</span></a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link {% if comments %}active{% endif %}" href="{% url 'activity:comments' %}" title="Comments"><i class="bi bi-chat"></i><span class="ms-1 d-md-inline d-none">COMMENTS</span></a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link {% if story_replies %}active{% endif %}" href="{% url 'activity:story_replies' %}" title="Story Replies"><i class="bi bi-arrow-90deg-left"></i><span class="ms-1 d-md-inline d-none">STORY REPLIES</span></a>
                        </li>
                    </ul>
                    <div class="mx-auto activity-area">
                      {% if likes %}
                        {% include 'activity/user-likes.html' %}
                      {% elif comments %}
                        {% include 'activity/user-comments.html' %}
                      {% elif story_replies_tab %}
                        {% include 'activity/user-story-replies.html' %}
                      {% endif %}
                  </div>
                </div>                
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/activity/photos.html
{% extends 'layouts/main-layout.html' %}
{% load static %}
{% load format_created_at %}
{% block content %}

<div class="container px-3">
    <div class="row mx-auto">
        <div class="col-12 col-lg-8 mx-auto my-3">
            <h3 class="fw-bold my-3">Your activity</h3>
            <div class="card rounded">
                <div class="card-body">
                    <ul class="nav nav-pills nav-justified mb-3">
                        <li class="nav-item">
                          <a class="nav-link {% if interactions %}active{% endif %}" aria-current="page" href="{% url 'activity:likes' %}"><i class="bi bi-arrow-left-right"></i>&nbsp;Interactions</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link {% if photos %}active{% endif %}" href="#"><i class="bi bi-images"></i>&nbsp;Photos</a>
                        </li>
                    </ul>
                    <ul class="nav nav-tabs justify-content-center">
                        <li class="nav-item">
                          <a class="nav-link {% if posts %}active{% endif %}" aria-current="page" href="{% url 'activity:posts' %}" title="Posts"><i class="bi bi-table"></i> <span class="ms-1 d-md-inline d-none">POSTS</span></a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link {% if highlights %}active{% endif %}" href="{% url 'activity:highlights' %}" title="Highlights"><i class="bi bi-circle"></i><span class="ms-1 d-md-inline d-none">HIGHLIGHTS</span></a>
                        </li>
                    </ul>
                    <div class="mx-auto activity-area">
                        {% if posts %}
                            {% include 'activity/user-posts.html' %}
                        {% elif highlights %}
                            {% include 'activity/user-highlights.html' %}
                        {% endif %}
                    </div>
                </div>                
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/activity/user-comments.html
{% load format_created_at %}
<div class="mt-5">
    <div class="me-5 mb-3 d-flex justify-content-end dropdown">
        <button class="btn btn-link text-decoration-none fw-bold" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Filter
        </button>
        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg-start rounded" aria-labelledby="navbarDropdown" style="width: 200px">
            <li><h6 class="dropdown-header">Categories</h6></li>
            <form action="" class="px-3">
                <li class="mb-2">
                    <div class="form-check">
                        <label class="form-check-label" for="flexCheckDefault">
                            All
                        </label>
                        <input class="form-check-input" type="radio" name="category" value="all" id="flexCheckDefault">
                    </div>
                </li>
                <li class="mb-2">
                    <div class="form-check">
                        <label class="form-check-label" for="flexCheckDefault">
                            Comments
                        </label>
                        <input class="form-check-input" type="radio" name="category" value="comments" id="flexCheckDefault">
                    </div>
                </li>
                <li class="mb-2">
                    <div class="form-check">
                        <label class="form-check-label" for="flexCheckDefault">
                            Replies
                        </label>
                        <input class="form-check-input" type="radio" name="category" value="replies" id="flexCheckDefault">
                    </div>
                </li>
                <li><hr class="dropdown-divider"></li>
                <button class="btn btn-primary btn-sm w-100 rounded">Apply</button>
            </form>
        </ul>
    </div>
    <div class="row activity-post-details">
        <div class="col-12 mx-5">
        {% for comment in all_comments %}
            {% if comment.post %}
                <ul class="list-group list-group-horizontal">
                    <li class="list-group-item" style="border: none">
                        <a href="{{ comment.post.user.get_absolute_url }}">
                            <img src={{comment.post.user.profile_photo.url}} alt="" class="post-profile-avatar"> 
                        </a>
                    </li>
                    <li class="list-group-item" style="border: none; width:500px">
                        <p> 
                            <a href="{{ comment.post.user.get_absolute_url }}" class="fw-bold text-decoration-none text-dark">{{comment.post.user.username}}</a> 
                            &nbsp;
                            <a href="{{comment.post.get_absolute_url}}" class="text-decoration-none text-dark">{{comment.post.caption}}</a>
                            <br>
                            <span class="text-muted small">{{comment.post.created_at|format_created_time}}</span>
                        </p>  
                    </li>
                    <li class="list-group-item " style="border: none;"> 
                        <a href="{{comment.post.get_absolute_url}}">
                            {% with image=comment.post.postimage_set.first %}
                                <img src="{{image.image.url}}" alt="{{comment.post.caption}}" style="width:48px;height:48px;object-fit: cover;">
                            {% endwith %}
                        </a>                            
                    </li>
                </ul> 
                <ul class="ms-5 list-group list-group-horizontal">
                    <li class="list-group-item" style="border: none">
                        <a href="{{ comment.user.get_absolute_url }}">
                            <img src={{comment.user.profile_photo.url}} alt="" class="post-profile-avatar"> 
                        </a>
                    </li>
                    <li class="list-group-item " style="border: none; width:500px">
                        <p> 
                            <a href="{{ comment.user.get_absolute_url }}" class="fw-bold text-decoration-none text-dark">{{comment.user.username}}</a> &nbsp;{{comment.body}}
                            <br>
                            <span class="text-muted small">{{comment.created_at|format_created_time}}</span>
                        </p>  
                    </li>
                </ul> 
            {% elif comment.comment %}
                <ul class="list-group list-group-horizontal">
                    <li class="list-group-item" style="border: none">
                        <a href="{{ comment.comment.post.user.get_absolute_url }}">
                            <img src={{comment.comment.post.user.profile_photo.url}} alt="" class="post-profile-avatar"> 
                        </a>
                    </li>
                    <li class="list-group-item" style="border: none; width:500px">
                        <p> 
                            <a href="{{ comment.comment.post.user.get_absolute_url }}" class="fw-bold text-decoration-none text-dark">{{comment.comment.post.user.username}}</a> &nbsp;
                            <a href="{{comment.comment.post.get_absolute_url}}" class="text-decoration-none text-dark">{{comment.comment.post.caption}}</a>
                            <br>
                            <span class="text-muted small">{{comment.comment.post.created_at|format_created_time}}</span>
                        </p>  
                    </li>
                    <li class="list-group-item " style="border: none;">
                        <a href="{{comment.comment.post.get_absolute_url}}">
                            {% with image=comment.comment.post.postimage_set.first %}
                                <img src="{{image.image.url}}" alt="{{comment.comment.post.caption}}" style="width:48px;height:48px;object-fit: cover;">
                            {% endwith %}
                        </a>
                    </li>
                </ul>
                <ul class="ms-5 list-group list-group-horizontal">
                    <li class="list-group-item" style="border: none">
                        <a href="{{ comment.comment.user.get_absolute_url }}">
                            <img src={{comment.comment.user.profile_photo.url}} alt="" class="post-profile-avatar"> 
                        </a>
                    </li>
                    <li class="list-group-item " style="border: none; width:500px">
                        <p> 
                            <a href="{{ comment.comment.user.get_absolute_url }}" class="fw-bold text-decoration-none text-dark">{{comment.comment.user.username}}</a> &nbsp;{{comment.comment.body}}
                            <br>
                            <span class="text-muted small">{{comment.comment.created_at|format_created_time}}</span>
                        </p>  
                    </li>
                </ul> 
                <ul class="ms-5 list-group list-group-horizontal">
                    <li class="list-group-item" style="border: none">
                        <a href="{{ comment.user.get_absolute_url }}">
                            <img src={{comment.user.profile_photo.url}} alt="" class="post-profile-avatar"> 
                        </a>
                    </li>
                    <li class="list-group-item " style="border: none; width:500px">
                        <p> 
                            <a href="{{ comment.user.get_absolute_url }}" class="fw-bold text-decoration-none text-dark">{{comment.user.username}}</a> &nbsp;{{comment.body}}
                            <br>
                            <span class="text-muted small">{{comment.created_at|format_created_time}}</span>
                        </p>  
                    </li>
                </ul> 
            {% endif %}
        {% endfor %}
        </div>
    </div>
</div>

templates/activity/user-highlights.html
<div class="mt-5">
    <div class="row g-1">
        {% for highlight in user_highlights %}
            <div class="col-4">
                <div class="card rounded-3 shadow-sm">
                    <div class="activity-highlight-image">
                        <a href="{% url 'story:highlight_details' highlight.slug highlight.get_first_story.slug %}" class="text-decoration-none text-light">
                            <img src="{{highlight.get_first_story.image.url}}" alt="{{highlight.name}}">
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

templates/activity/user-likes.html
<div class="mt-5">
    <div class="row g-1">
        {% for post in liked_posts %}
            <div class="col-4">
                <div class="card rounded shadow-sm">
                    <div class="activity-post-image">
                        <a href="{{post.get_absolute_url}}" class="text-decoration-none text-light" style="display: inline;position:relative;">
                            {% with image=post.postimage_set.all %}
                                <img src="{{image.first.image.url}}" class="card-img" alt="{{post.caption}}">
                                {% if image.count > 1 %}
                                    <i class="fas fa-clone mx-2 my-2" style="position:absolute;right: 0;"></i>
                                {% endif %}
                            {% endwith %}
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

templates/activity/user-posts.html
<div class="mt-5">
    <div class="row g-1">
        {% for post in user_posts %}
            <div class="col-4">
                <div class="card rounded shadow-sm">
                    <div class="activity-post-image">
                        <a href="{{post.get_absolute_url}}" class="text-decoration-none text-light" style="display: inline;position:relative;">
                            {% with image=post.postimage_set.all %}
                                <img src="{{image.first.image.url}}" class="card-img" alt="{{post.caption}}">
                                {% if image.count > 1 %}
                                    <i class="fas fa-clone mx-2 my-2" style="position:absolute;right: 0;"></i>
                                {% endif %}
                            {% endwith %}
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

templates/activity/user-story-replies.html
{% load format_created_at %}
<div class="mt-5">
    <div class="row activity-post-details">
        <div class="col-12 mx-5">
        {% for reply in story_replies %}
            <ul class="list-group list-group-horizontal">
                <li class="list-group-item" style="border: none">
                    <a href="{{ reply.user.get_absolute_url }}">
                        <img src={{reply.user.profile_photo.url}} alt="" class="post-profile-avatar"> 
                    </a>
                </li>
                <li class="list-group-item" style="border: none; width:500px">
                    <p> 
                        <a href="{{ reply.user.get_absolute_url }}" class="fw-bold text-decoration-none text-dark">{{reply.user.username}}</a> 
                        &nbsp;
                        replied <b>{{reply.body}}</b> on story from <a href="{{reply.story.user.get_absolute_url}}" class="fw-bold text-decoration-none text-dark">{{reply.story.user.username}}</a>
                        <br>
                        <span class="text-muted small">{{reply.created_at|format_created_time}}</span>
                    </p>  
                </li>
                <li class="list-group-item " style="border: none;"> 
                    <a href="{{reply.story.get_absolute_url}}">
                        <img src="{{reply.story.image.url}}" alt="{{reply.post.caption}}" style="width:48px;height:48px;object-fit: cover;">
                    </a>                            
                </li>
            </ul> 
        {% endfor %}
        </div>
    </div>
</div>