chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('inbox/', views.inbox, name='inbox'),
    path('t/<slug:slug>/', views.chat, name='chat'),
    path('send-message/', views.send_message, name='send_message'),
    path('new-chat/', views.new_chat, name='new_chat'),
    # path('get/users/', views.get_users, name='get_users')
]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views as user_views
from search import views as search_views
from post import views as post_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('feed.urls', namespace='feed')),
    path('accounts/', include('account.urls', namespace='account')),
    path('p/', include('post.urls', namespace='post')),
    path('direct/', include('chat.urls', namespace='chat')),
    path('user/', include('user.urls', namespace='user')),
    path('stories/', include('story.urls', namespace='story')),
    path('notification/', include('notification.urls', namespace='notification')),
    path('your-activity/', include('activity.urls', namespace='activity')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),

    # user views
    path('<str:username>/', user_views.profile, name='profile'),
    path('<str:username>/saved/', user_views.user_saved, name='user_saved'),
    path('explore/people/', user_views.suggestions, name='suggestions'),

    # post views
    path('explore/p/', post_views.explore, name='explore'),

    # search views
    path('search', search_views.search, name='search'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('create/', views.create_post, name='create_post'),
    path('<slug:slug>/', views.post_details, name='post_details'),
    path('<slug:slug>/comments/', views.get_post_comments, name='post_comments'),
    path('add-comment/<str:pk>/', views.add_comment, name='add_comment'),
    path('delete-comment/<str:pk>/', views.delete_comment, name='delete_comment'),
    path('add-like/<str:pk>/', views.add_like, name='add_like'),
    path('add-bookmark/<str:pk>/', views.add_bookmark, name='add_bookmark'),
    path('delete/<str:pk>/', views.delete_post, name='delete_post'),
    path('update/<slug:slug>/', views.update_post, name='update_post'),
    path('like-comment/<str:pk>/', views.like_comment, name='like_comment'),
    path('add-favorite/<str:user_id>/', views.add_favorites, name='add_favorites'),
    path('add-reply/<str:pk>/', views.add_reply, name='add_reply'),
    path('delete-reply/<str:pk>/', views.delete_reply, name='delete_reply'),
    path('like-reply/<str:pk>/', views.like_reply, name='like_reply'),
]

story/urls.py
from django.urls import path
from . import views
from user import views as user_views

app_name = 'story'

urlpatterns = [
    path('details/<str:username>/<slug:slug>/', views.story_details, name='story_details'),
    path('add-to-story/', views.add_to_story, name='add_to_story'),
    path('like-story/<slug:slug>/', views.like_story, name='like_story'),
    path('reply-story/<slug:slug>/', views.reply_to_story, name='reply_to_story'),
    path('delete-story/<slug:slug>/', views.delete_story, name='delete_story'),
    path('highlights/<slug:slug>/<slug:story_slug>/', user_views.highlight_details, name='highlight_details'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [    
    path('follow/<str:user_id>/', views.follow, name='follow'),
    path('unfollow/<str:username>/', views.unfollow, name='unfollow'),
    path('remove/follower/<str:user_id>/', views.remove_follower, name='remove_follower'),
    path('upload-photo/<str:username>/', views.upload_profile_photo, name='upload_profile_photo'),
    path('create-highlight/<str:username>/', views.create_highlight, name='create_highlight'),
    path('edit-highlight/<slug:slug>/', views.edit_highlight, name='edit_highlight'),
    path('delete-highlight/<slug:slug>/', views.delete_highlight, name='delete_highlight'),
]

post/models.py
from django.db import models
from commons.models import TimeStampModel, StatusModel
from django.contrib.auth.models import BaseUserManager
from django.conf import settings
from .random_slug import generate_random_slug
from django.urls import reverse

# Create your models here.

User = settings.AUTH_USER_MODEL

class Post(TimeStampModel, StatusModel):
    caption = models.CharField(max_length=255, blank=True, null=True)
    slug = models.SlugField(max_length=255, db_index=True, unique=True, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    likes = models.ManyToManyField(User, related_name='post_likes', blank=True)

    def __str__(self):
        return self.caption

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = generate_random_slug()
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('post:post_details', kwargs={'slug':self.slug})
    
    @property
    def get_like_url(self):
        return reverse('post:add_like', args=[self.id])
    
    @property
    def get_bookmark_url(self):
        return reverse('post:add_bookmark', args=[self.id])

    class Meta:
        ordering = ['-created_at']


class PostImage(TimeStampModel, StatusModel):
    image = models.ImageField(upload_to='post', blank=True, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.post.caption

class CommentManager(BaseUserManager):
    def get_queryset(self):
        return super().get_queryset().filter(status=True)
    
    
class Comment(TimeStampModel, StatusModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_comments', blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comments', blank=True, null=True)
    body = models.TextField(max_length=255, blank=True, null=True)
    likes = models.ManyToManyField(User, related_name='comment_likes', blank=True)
    objects = CommentManager()

    def __str__(self):
        return f"{self.user} commented on '{self.post}': '{self.body}'"


class Reply(TimeStampModel, StatusModel):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='comment_replies', blank=True, null=True)
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='reply_replies', blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_replies', blank=True, null=True)
    body = models.TextField(max_length=255, blank=True, null=True)
    likes = models.ManyToManyField(User, related_name='reply_likes', blank=True)
    objects = CommentManager()

    class Meta:
        ordering = ['created_at']
        verbose_name_plural = 'replies'

    @property
    def replied_user(self):
        return self.reply.user if self.reply else self.comment.user

    def __str__(self):
        return f"{self.user} replied to your comment '{self.comment}': '{self.body}'"

story/models.py
from django.db import models
from commons.models import TimeStampModel, StatusModel
from django.contrib.auth.models import BaseUserManager
from django.conf import settings
from post.random_slug import generate_random_slug
from django.urls import reverse

# Create your models here.

User = settings.AUTH_USER_MODEL

class Story(TimeStampModel, StatusModel):
    caption = models.CharField(max_length=500, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    slug = models.SlugField(max_length=255, db_index=True, unique=True, blank=True, null=True)
    image = models.ImageField(upload_to='story', blank=True, null=True)
    likes = models.ManyToManyField(User, related_name='story_likes', blank=True)
    views = models.ManyToManyField(User, related_name='story_viewers', blank=True)

    def __str__(self):
        return f"{self.user}'s story - {self.caption}"
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = generate_random_slug()
        super(Story, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('story:story_details', kwargs={'username':self.user.username, 'slug':self.slug})

    class Meta:
        ordering = ['created_at']
        verbose_name_plural = 'stories'


class StoryReply(TimeStampModel, StatusModel):
    story = models.ForeignKey(Story, on_delete=models.CASCADE, related_name='story_replies', blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    body = models.TextField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"{self.user}'s reply"

    class Meta:
        ordering = ['-created_at']

    

user/models.py
from django.db import models
from commons.models import StatusModel, TimeStampModel
from django.conf import settings
from story.models import Story
from post.random_slug import generate_random_slug

# Create your models here.

User = settings.AUTH_USER_MODEL

class Highlight(StatusModel, TimeStampModel):
    name = models.CharField(max_length=255, blank=True, null=True)
    slug = models.SlugField(max_length=255, db_index=True, unique=True, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    stories = models.ManyToManyField(Story, related_name='story_highlights', blank=True)

    def __str__(self):
        return f"{self.user}'s highlight - {self.name}"
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = generate_random_slug()
        super(Highlight, self).save(*args, **kwargs)

    @property
    def get_first_story(self):
        return self.stories.order_by('created_at').first()

user/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.db.models import Q, Count
from account.models import Profile
from account.forms import UserEditForm
from post.models import Post
from django.contrib.auth.decorators import login_required
from commons.decorators import normal_user_only
from .models import Highlight
from story.models import Story
from .decorators import highlight_user_required, user_required
from chat.utils import get_inbox

# Create your views here.

@normal_user_only
def profile(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    print(True if user.profile_photo else False)
    title = f'{user.name} (@{user.username}) | Instagram'
    user_posts = Post.objects.filter(user=user, status=True).order_by('-created_at')
    stories_count = Story.objects.filter(user = user).count()
    highlights = Highlight.objects.filter(user = user, status = True).order_by('-created_at').all()
    user_posts_count = user_posts.count()
    inbox = None
    if request.user != user:
        inbox = get_inbox(request.user, user)
    context = {'user':user, 'title':title, 'user_profile':True, 'user_posts':user_posts,
               'user_posts_count':user_posts_count, 'highlights':highlights, 'stories_count':stories_count, 'inbox':inbox}
    return render(request, 'user/profile/profile.html', context=context)

@login_required
@normal_user_only
@user_required
def user_saved(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    title = f'{user.name} (@{user.username}) \u2022 Instagram photos and videos'
    user_posts = Post.objects.filter(user=user, status=True).order_by('-created_at')
    stories_count = Story.objects.filter(user = user).count()
    highlights = Highlight.objects.filter(user = user, status = True).order_by('-created_at').all()
    user_posts_count = user_posts.count()
    user_bookmarks = user.profile.bookmarks.filter(status=True)
    context = {'user':user, 'title':title, 'user_bookmarks':user_bookmarks, 'bookmark':True, 
               'user_posts_count':user_posts_count, 'highlights':highlights, 'stories_count':stories_count}
    return render(request, 'user/profile/profile.html', context=context)

@login_required
def edit_profile(request):
    user = get_object_or_404(get_user_model(), username=request.user.username)
    form = UserEditForm(instance=user)
    if request.method == 'POST':
        form = UserEditForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated successfully.')
            return redirect('profile', username=user.username)
    context = {'form':form, 'user':user, 'edit_profile':True}
    return render(request, 'user/edit-profile.html', context=context)

@login_required
@normal_user_only
def upload_profile_photo(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    if request.method == 'POST':
        if request.FILES.get('profile_photo') is not None:
            uploaded_photo = request.FILES.get('profile_photo')
            user.profile_photo = uploaded_photo
            user.save()
            messages.success(request, 'Profile picture updated successfully.')
        else:
            messages.error(request, 'Please select an image to continue.')
    return redirect(request.META.get('HTTP_REFERER'))

@login_required
@normal_user_only
def suggestions(request):
    suggestions = get_user_model().objects.exclude(Q(id__in=request.user.profile.followings.all())|Q(id=request.user.id)|Q(is_superuser=True))
    context={'suggestions':suggestions}
    return render(request, 'user/suggestions.html', context=context)

@login_required
@normal_user_only
def follow(request, user_id):
    user = get_object_or_404(get_user_model(), id=user_id)
    if user not in request.user.profile.followings.all():
        request.user.profile.followings.add(user_id)
        user.profile.followers.add(request.user)
    return redirect(request.META.get('HTTP_REFERER'))

@login_required
@normal_user_only
def unfollow(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    if request.method == 'POST':
        if user in request.user.profile.followings.all():
            request.user.profile.followings.remove(user)
            user.profile.followers.remove(request.user)
            return redirect('profile', request.user.username)
    context = {'user':user}
    return render(request, 'user/unfollow.html',context=context)

@login_required
@normal_user_only
def remove_follower(request, user_id):
    user = get_object_or_404(get_user_model(), id=user_id)
    if user in request.user.profile.followers.all():
        request.user.profile.followers.remove(user_id)
        user.profile.followings.remove(request.user)
    return redirect(request.META.get('HTTP_REFERER'))

@login_required
@normal_user_only
def create_highlight(request, username):
    user = get_user_model().objects.select_related('profile').filter(username = username, is_active = True).first()
    if request.method == 'POST':
        name = request.POST.get('highlight_name')
        _stories = request.POST.getlist('story')
        if len(_stories) > 0:
            highlight = Highlight.objects.create(name = name, user = user)
            stories = Story.objects.filter(id__in = _stories, user = user).all()
            highlight.stories.add(*stories)
            messages.info(request, 'Highlight added.')
        else:
            messages.warning(request, 'Please select atleast one story.')
    return redirect(request.META.get('HTTP_REFERER'))

@login_required
@normal_user_only
def highlight_details(request, slug, story_slug):
    highlight = get_object_or_404(Highlight, slug = slug)
    story = get_object_or_404(Story, slug=story_slug)
    highlight_stories = Story.objects.filter(id__in = highlight.stories.all()).all()

    prev_story = Story.objects.filter(id__in = highlight.stories.all(), created_at__lt = story.created_at,).last()
    next_story = Story.objects.filter(id__in = highlight.stories.all(), created_at__gt = story.created_at,).first()

    context = {'highlight':highlight, 'story':story, 'highlight_stories':highlight_stories, 
               'prev_story':prev_story, 'next_story':next_story, 'title':'Stories', 'highlight_page':True}
    return render(request, 'user/highlight-details.html', context=context)

@login_required
@normal_user_only
@highlight_user_required
def edit_highlight(request, slug):
    highlight = get_object_or_404(Highlight, slug=slug)
    if request.method == 'POST':
        name = request.POST.get('highlight_name')
        _stories = request.POST.getlist('story')
        if name != highlight.name:
            highlight.name = name
            highlight.save()
        stories = Story.objects.filter(id__in = _stories)
        for story in stories:
            if story not in highlight.stories.all():
                highlight.stories.add(story)
    return redirect('profile', username=highlight.user.username)

@login_required
@normal_user_only
@highlight_user_required
def delete_highlight(request, slug):
    highlight = get_object_or_404(Highlight, slug=slug)
    highlight.delete()
    return redirect('profile', username = highlight.user.username)

templates/user/follower-modal.html
<!-- Follower Modal -->
{% load static %}
<div class="modal" id="followers-{{user.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered">
        <div class="modal-content rounded">
            <div class="modal-header text-center">
                <div class="modal-title w-100">
                    Followers
                </div>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <ol class="list-group list-group-flush">
                    {% for follower in user.profile.followers.all %}
                        <li class="list-group-item d-flex justify-content-between align-items-start" style="border: none">
                            <a href="{{follower.get_absolute_url }}" class="text-decoration-none text-dark">
                                <img src={{follower.profile_photo.url}} alt="" class="post-profile-avatar">
                                <div class="ms-2 me-auto fs-6">
                                    <div class="fw-bold">
                                        {{follower.username}}</a>
                                {% if follower not in request.user.profile.followings.all and user == request.user %}
                                    &bull; <a href="{% url 'user:follow' follower.id %}" class="text-decoration-none">Follow</a>
                                {% endif %}
                                </div>
                                <span class="text-muted">{{follower.name}}</span>
                            </div>
                            {% if user == request.user  %}
                                <span>
                                    <a onclick="window.location.href='{{follower.get_remove_follower_url}}'" class="fw-bold btn btn-light btn-sm border rounded">Remove</a>
                                </span>
                            {% endif %}
                            {% if follower != request.user and user != request.user %}
                                {% if follower in request.user.profile.followings.all %}
                                    <a href="{% url 'user:unfollow' follower.username %}" class="fw-bold btn btn-light btn-sm border rounded">Following</a>
                                {% else %}
                                    <a onclick="window.location.href='{{follower.get_follow_url}}'" class="fw-bold btn btn-primary btn-sm rounded">Follow</a>
                                {% endif %}
                            {% endif %}
                        </li>
                    {% endfor %}
                </ol>
            </div>
        </div>
    </div>
</div>

templates/user/following-modal.html
<!-- Post Options Modal -->
{% load static %}
<div class="modal" id="following-{{user.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered">
        <div class="modal-content rounded">
            <div class="modal-header text-center">
                <div class="modal-title w-100">
                    Following
                </div>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <ol class="list-group list-group-flush">
                    {% for following in user.profile.followings.all %}
                        <li class="list-group-item d-flex justify-content-between align-items-start" style="border: none">
                            <a href="{{ following.get_absolute_url }}" class="text-decoration-none text-dark">
                            <img src={{following.profile_photo.url}} alt="" class="post-profile-avatar">
                            <div class="ms-2 me-auto fs-6">
                                <div class="fw-bold">{{following.username}}</a></div>
                                <span class="text-muted">{{following.name}}</span>
                            </div>
                            <span>
                                {% if following != request.user %}
                                    {% if following in request.user.profile.followings.all %}
                                        <a href="{% url 'user:unfollow' following.username %}" class="fw-bold btn btn-light btn-sm border rounded">Following</a>
                                    {% else %}
                                        <a href="{% url 'user:follow' following.id %}" class="fw-bold btn btn-primary btn-sm rounded">Follow</a>
                                    {% endif %}
                                {% endif %}
                            </span>
                        </li>
                    {% endfor %}
                </ol>
            </div>
        </div>
    </div>
</div>

templates/user/highlight-details.html
{% extends 'layouts/story-layout.html' %}
{% load static %}
{% load format_created_at %}
{% block content %}

<div class="row">
  <div class="col-md-10 mx-auto px-3">
      <div class="row">
          <div class="col-md-6 px-3 mx-auto">
            <div class="card shadow rounded border-info">
              <div class="story-image">
                <img src="{{story.image.url}}" class="card-img-top" alt="...">
              </div>
              <div class="card-img-overlay text-center story-image">
                <h5 class="card-title fw-bold fs-1">{{story.caption}}</h5>
              </div>
              <div class="card-body text-center">
                <div class="d-flex justify-content-between mb-4 px-3">
                  <a href="{{ story.user.get_absolute_url }}" class="d-flex justify-content-start text-decoration-none text-dark">
                      <img src="{{story.user.profile_photo.url}}" class="me-2 post-profile-avatar">
                      <h6 class="fw-bold pt-2">{{story.user.username}}
                        &bull;
                        <small class="text-muted">{{story.created_at|format_created_time}}</small>
                      </h6>
                  </a>
                  <div class="dropdown">
                    <i class="fas fa-ellipsis-h pt-2" data-bs-toggle="dropdown" data-bs-auto-close="outside" style="cursor:pointer;"></i>
                    {% include 'user/highlight-options-dropdown.html' %}
                  </div>
                </div>
              </div>
            </div>
          </div>
      </div>
  </div>
</div>

<div class="d-flex justify-content-between text-center mt-2">
  {% if prev_story %}
    <a href="{% url 'story:highlight_details' highlight.slug prev_story.slug %}" class="btn btn-dark btn-sm rounded">&#8249;</a>
  {% else %}
    <a href="#" class="btn btn-dark btn-sm rounded float-start disabled">&#8249;</a>
  {% endif %}

  <div class="text-center mx-auto">
    {% for highlight_story in highlight_stories %}
      {% if highlight_story.id == story.id %}
        {{forloop.counter}} of {{highlight_stories.count}}
      {% endif %}
    {% endfor %}
  </div>

  {% if next_story %}
    <a href="{% url 'story:highlight_details' highlight.slug next_story.slug %}" class="btn btn-dark btn-sm rounded">&#8250;</a>
  {% else %}
    <a href="#" class="btn btn-dark btn-sm rounded float-end disabled">&#8250;</a>
  {% endif %}
</div>

{% endblock content%}

templates/user/highlight-options-dropdown.html
<!-- Post Options Dropdown -->
{% load static %}
<ul class="dropdown-menu dropdown-menu-start dropdown-menu-lg-end text-center rounded">
    {% if request.user == highlight.user %}
        <a href="{% url 'user:delete_highlight' highlight.slug %}" class="dropdown-item text-danger fw-bold">Delete</a>
        <a href="#" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#edit-highlight">Edit</a>
    {% else %}
        <a href="#" class="dropdown-item text-danger fw-bold">Report</a>
    {% endif %}
</ul>
{% include 'user/highlights-edit-modal.html' %}

templates/user/highlights-create-modal.html
<div class="modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" id="create-highlight">
    <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered modal-lg">
        <div class="modal-content rounded-4">
          <div class="modal-header text-center">
            <h6 class="modal-title w-100">New Highlight</h6>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form method="post" action="{% url 'user:create_highlight' user.username %}" class="px-3">
                {% csrf_token %}
                <div class="form-floating mb-3">
                    <input type="text" class="form-control rounded" id="floatingInput" placeholder="Highlight Name" name="highlight_name" required>
                    <label for="floatingInput">Highlight Name</label>
                </div>
                <p class="fw-bold mb-3">Stories</p>
                <div class="row g-3">
                    {% for story in user.story_set.all %}
                        <div class="col-6 mb-3">
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="exampleCheck1" name="story" value="{{story.id}}">
                                <label class="form-check-label" for="exampleCheck1">{{story.caption|truncatewords:5}}</label>
                            </div>
                            <div class="related-post-image">
                                <img src="{{story.image.url}}" alt="{{story.caption}}">
                            </div>
                        </div>
                    {% endfor %}
                </div>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-link text-decoration-none fw-bold w-100">Done</button>
          </div>
            </form>
        </div>
    </div>
</div>

templates/user/highlights-edit-modal.html
<div class="modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" id="edit-highlight">
    <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered modal-lg">
        <div class="modal-content rounded-4">
          <div class="modal-header text-center">
            <h6 class="modal-title w-100">Edit Highlight</h6>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form method="post" action="{% url 'user:edit_highlight' highlight.slug %}" class="px-3">
                {% csrf_token %}
                <div class="form-floating mb-3">
                    <input type="text" class="form-control rounded" id="floatingInput" placeholder="Highlight Name" name="highlight_name" value="{{highlight.name}}" required>
                    <label for="floatingInput">Highlight Name</label>
                </div>
                <p class="fw-bold mb-3">Stories</p>
                <div class="row g-3">
                    {% for story in user.story_set.all %}
                        <div class="col-6 mb-3">
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="exampleCheck1" name="story" value="{{story.id}}" {% if story in highlight.stories.all %}checked{% endif %}>
                                <label class="form-check-label" for="exampleCheck1">{{story.caption|truncatewords:5}}</label>
                            </div>
                            <div class="related-post-image">
                                <img src="{{story.image.url}}" alt="{{story.caption}}">
                            </div>
                        </div>
                    {% endfor %}
                </div>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-link text-decoration-none fw-bold w-100">Done</button>
          </div>
            </form>
        </div>
    </div>
</div>

templates/user/highlights.html
{% load static %}
<div class="my-3 px-1">
    <div class="story-block">
        <ul class="list-group list-group-horizontal list-group-flush">
            {% if highlights %}
                {% for highlight in highlights %}
                    <li class="list-group-item text-center me-1" style="border: none">
                        <a href="{% url 'story:highlight_details' highlight.slug highlight.get_first_story.slug %}">
                            <img src="{{highlight.get_first_story.image.url}}" alt="" 
                            class="higlights-avatar border border-3">
                        </a>
                        <br>
                        <small data-bs-toggle="tooltip" data-bs-placement="top" title="{{highlight.name}}">{% if highlight.name|length > 12 %}{{highlight.name|slice:':10'}}...{% else %}{{highlight.name}}{% endif %}</small>
                    </li>
                {% endfor %}
            {% endif %}
            {% if user == request.user %}
                <li class="list-group-item text-center" style="border: none">
                    <a>
                        <img src="{% static 'images/plus.png' %}" alt="" 
                        class="higlights-avatar border border-3"
                        data-bs-toggle="modal" data-bs-target="#create-highlight">
                    </a>
                    <br>
                    <small>New</small>
                </li>
            {% endif %}
        </ul>
    </div>
</div>